/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERC20Permit } from "./ERC20Permit";
export type { IERC20Permit } from "./IERC20Permit";
export type { ITestGDAO } from "./ITestGDAO";
export type { TestGDAO } from "./TestGDAO";
