[profile.default]
ffi = true
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'interfaces/=src/interfaces',
    'modules/=src/modules',
    'policies/=src/policies',
    'libraries/=src/libraries',
    'solmate/=lib/solmate/src/',
    'balancer-v2/=lib/balancer-v2/',
    'layer-zero/=lib/solidity-examples/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'bonds/=lib/bonds/src/',
    'test/=src/test/',
    'clones/=lib/clones-with-immutable-args/src/',
    '@uniswap/v3-core/=lib/uniswap-v3-core/',
    '@uniswap/v3-periphery/=lib/uniswap-v3-periphery/',
]
fs_permissions = [
    {access = "write", path = "./src/test/sim/out/"},
    {access = "write", path = "./deployments/"},
    {access = "read", path = "./src/scripts/"}
]
solc_version = "0.8.15"
optimizer = true
# Default is 200
optimizer_runs = 10

[fuzz]
runs = 256