[profile.default]
ffi = true
ast = true
legacy_assertions = true
assertions_revert = false
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'interfaces/=src/interfaces',
    'modules/=src/modules',
    'policies/=src/policies',
    'libraries/=src/libraries',
    'solmate/=lib/solmate/src/',
    'balancer-v2/=lib/balancer-v2/',
    'layer-zero/=lib/solidity-examples/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'bonds/=lib/bonds/src/',
    'clones/=lib/clones-with-immutable-args/src/',
    'proposal-sim/=lib/forge-proposal-simulator/',
]
fs_permissions = [
    {access = "write", path = "./src/test/sim/out/"},
    {access = "write", path = "./deployments/"},
    {access = "read", path = "./src/scripts/"},
    {access = "read", path = "./src/proposals/addresses.json"},
]

# The solc version was previously explicitly set, but has now been moved to `compilation_restrictions` in order to compile some contracts with 0.8.24
# solc_version = "0.8.15"

optimizer = true
optimizer_runs = 10000
chain_id = 1
verbosity = 3

# Operator is too large - it needs to only use 10 optimizer runs
additional_compiler_profiles = [
    { name = "ten-runs", optimizer_runs = 10 },
    { name = "five-thousand-runs", optimizer_runs = 5000 },
]
compilation_restrictions = [
    { paths = "src/policies/Operator.sol", profile = "ten-runs" },
    { paths = "src/policies/cooler/MonoCooler.sol", profile = "five-thousand-runs" },
    { paths = "**", version = "0.8.15" },
]

[fuzz]
runs = 256

[soldeer]
remappings_generate = false

[dependencies]
surl = { version = "1.0.0", git = "https://github.com/memester-xyz/surl.git", rev = "034c912ae9b5e707a5afd21f145b452ad8e800df" }
base64 = { version = "1.1.0", git = "https://github.com/Brechtpd/base64.git", rev = "4d85607b18d981acff392d2e99ba654305552a97" }
clones-with-immutable-args = { version = "1.1.2", git = "https://github.com/wighawag/clones-with-immutable-args.git", rev = "196f1ecc6485c1bf2d41677fa01d3df4927ff9ce" }
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.3.0"
