[profile.default]
ffi = true
ast = true
legacy_assertions = true
assertions_revert = false
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'interfaces/=src/interfaces',
    'modules/=src/modules',
    'policies/=src/policies',
    'libraries/=src/libraries',
    'solmate/=lib/solmate/src/',
    'balancer-v2/=lib/balancer-v2/',
    'layer-zero/=lib/solidity-examples/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'bonds/=lib/bonds/src/',
    'clones/=lib/clones-with-immutable-args/src/',
    'proposal-sim/=lib/forge-proposal-simulator/',
]
fs_permissions = [
    {access = "write", path = "./src/test/sim/out/"},
    {access = "write", path = "./deployments/"},
    {access = "read", path = "./src/scripts/"},
    {access = "read", path = "./src/proposals/addresses.json"},
]
solc_version = "0.8.15"
optimizer = true
optimizer_runs = 10000
chain_id = 1
verbosity = 3

# Operator is too large - it needs to only use 10 optimizer runs
additional_compiler_profiles = [ { name = "ten-runs", optimizer_runs = 10 } ]
compilation_restrictions = [
    { paths = "src/policies/Operator.sol", optimizer_runs = 10 },
]

[fuzz]
runs = 256

[soldeer]
remappings_generate = false

[dependencies]
surl = { version = "1.0.0", git = "https://github.com/memester-xyz/surl.git", rev = "034c912ae9b5e707a5afd21f145b452ad8e800df" }
