/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EggsFullProtec } from "./EggsFullProtec";
export type { IERC20 } from "./IERC20";
export type { IERC20Permit } from "./IERC20Permit";
export type { IEggsToken } from "./IEggsToken";
export type { Ownable } from "./Ownable";
