// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.15;

import {ERC20} from "solmate/tokens/ERC20.sol";

contract MockEasyAuction {
    // ========= DATA STRUCTURES ========= //
    struct AuctionData {
        ERC20 auctioningToken;
        ERC20 biddingToken;
        uint256 orderCancellationEndDate;
        uint256 auctionEndDate;
        uint256 minimumBiddingAmountPerOrder;
        bool minFundingThresholdNotReached;
        bool isAtomicClosureAllowed;
        uint256 minFundingThreshold;
    }

    // ========= STATE ========= //
    // This was public, which generated a nine-value getter that exhausted the stack without the
    // optimizer. Keep it internal and expose only the three values the tests need below.
    mapping(uint256 => AuctionData) internal _auctionData;
    uint256 public auctionCounter;

    constructor() {}

    // This was external with calldata parameters. Public with memory parameters preserves the
    // external ABI while avoiding the stack-heavy unoptimized calldata decoder generated by solc.
    function initiateAuction(
        ERC20 tokenToSell,
        ERC20 biddingToken,
        uint256 lastCancellation,
        uint256 auctionEnd,
        uint96 auctionAmount,
        uint96 minimumTotalPurchased,
        uint256 minimumPurchaseAmount,
        uint256 minFundingThreshold,
        bool isAtomicClosureAllowed,
        address accessManager,
        bytes memory accessManagerData
    ) public returns (uint256) {
        ++auctionCounter;

        _auctionData[auctionCounter] = AuctionData(
            tokenToSell,
            biddingToken,
            lastCancellation,
            auctionEnd,
            minimumPurchaseAmount,
            false,
            isAtomicClosureAllowed,
            minFundingThreshold
        );

        tokenToSell.transferFrom(msg.sender, address(this), auctionAmount);
        return auctionCounter;
    }

    // This replaces the former full-struct mapping getter with the narrow test-facing result.
    function getAuctionSummary(
        uint256 auctionId
    )
        external
        view
        returns (ERC20 biddingToken, uint256 orderCancellationEndDate, uint256 auctionEndDate)
    {
        AuctionData storage data = _auctionData[auctionId];
        return (data.biddingToken, data.orderCancellationEndDate, data.auctionEndDate);
    }

    function settleAuction(uint256 auctionId) external returns (bytes32) {
        return bytes32(0);
    }
}
