/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITestGDAO__factory } from "./ITestGDAO__factory";
export { TestGDAO__factory } from "./TestGDAO__factory";
