/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GDAOStaking } from "./GDAOStaking";
export type { IDistributor } from "./IDistributor";
export type { IOlympusAuthority } from "./IOlympusAuthority";
export type { OlympusAccessControlled } from "./OlympusAccessControlled";
