/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BondCallbackTest__factory } from "./BondCallbackTest__factory";
export { MockGdao__factory } from "./MockGdao__factory";
