/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERC20Permit } from "./ERC20Permit";
export type { SGDAO } from "./SGDAO";
