name: CI
on:
    push:
        branches:
            - master
    pull_request:

env:
    ETH_MAINNET_RPC_URL: ${{ secrets.ETH_MAINNET_RPC_URL }}
    POLYGON_MAINNET_RPC_URL: ${{ secrets.POLYGON_MAINNET_RPC_URL }}

jobs:
    run-ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: actions/setup-node@v2

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Install Node dependencies
              run: pnpm install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly-ca67d15f4abd46394b324c50e21e66f306a1162d

            - name: Install Foundry dependencies
              run: forge install

            - name: Build
              run: forge build --ast

            - name: Run lint check
              run: pnpm run lint:check

            - name: Run unit tests
              run: pnpm run test:unit

            - name: Run proposal simulation tests
              run: pnpm run test:proposal
              env:
                  FORK_TEST_RPC_URL: ${{ secrets.FORK_TEST_RPC_URL }}

            - name: Run fork tests
              run: pnpm run test:fork
              env:
                  FORK_TEST_RPC_URL: ${{ secrets.FORK_TEST_RPC_URL }}

            - name: Run cross-chain fork tests
              run: pnpm run test:crosschainfork
