name: CI
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    run-ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install deps
              run: forge install

            - name: Install Foundry
              uses: onbjerg/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Run lint check
              run: npm run lint:check

            - name: Run tests
              run: forge test
