name: CI
on:
    push:
        branches:
            - master
    pull_request:

env:
  ETH_MAINNET_RPC_URL: ${{ secrets.ETH_MAINNET_RPC_URL }}
  POLYGON_MAINNET_RPC_URL: ${{ secrets.POLYGON_MAINNET_RPC_URL }}

jobs:
    run-ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - uses: actions/setup-node@v2

            - uses: pnpm/action-setup@v2
              with:
                version: 8

            - name: Install Node dependencies
              run: pnpm install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly-ca67d15f4abd46394b324c50e21e66f306a1162d

            - name: Install Foundry dependencies
              run: forge install

            - name: Run lint check
              run: pnpm run lint:check

            - name: Run non-fork tests
              run: pnpm run test:unit

            - name: Run fork tests
              run: pnpm run test:fork
              env:
                FORK_TEST_RPC_URL: ${{ secrets.FORK_TEST_RPC_URL }}

            - name: Run cross-chain fork tests
              run: pnpm run test:crosschainfork

            # FYI: currently version 1.14
            - name: Setup lcov
              uses: hrishikesh-kadam/setup-lcov@v1

            - name: Run Code Coverage
              run: pnpm run test:coverage

            - uses: actions/upload-artifact@v3
              with:
                name: lcov-pruned.info
                path: lcov-pruned.info
              
            - name: Report Code Coverage
              uses: kefasjw/lcov-pull-request-report@v1
              with:
                lcov-file: lcov-pruned.info
                github-token: ${{ secrets.GITHUB_TOKEN }}
