name: CI
on:
    push:
        branches:
            - master
    pull_request:

env:
  ETH_MAINNET_RPC_URL: ${{ secrets.ETH_MAINNET_RPC_URL }}
  POLYGON_MAINNET_RPC_URL: ${{ secrets.POLYGON_MAINNET_RPC_URL }}

jobs:
    run-ci:
        runs-on: ubuntu-latest

        permissions:
          # Give the default GITHUB_TOKEN write permission to commit and push the
          # added or changed files to the repository.
          contents: write

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
                  ref: ${{ github.head_ref }} # Prevents checkout in detatched HEAD state. The Commit Code Coverage step requires a branch to commit to.

            - uses: actions/setup-node@v2

            - uses: pnpm/action-setup@v2
              with:
                version: 8

            - name: Install Node dependencies
              run: pnpm install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly-ca67d15f4abd46394b324c50e21e66f306a1162d

            - name: Install Foundry dependencies
              run: forge install

            - name: Run lint check
              run: pnpm run lint:check

            - name: Run non-fork tests
              run: pnpm run test:unit

            - name: Run fork tests
              run: pnpm run test:fork
              env:
                FORK_TEST_RPC_URL: ${{ secrets.FORK_TEST_RPC_URL }}

            - name: Run cross-chain fork tests
              run: pnpm run test:crosschainfork

            # FYI: currently version 1.14
            - name: Setup lcov
              uses: hrishikesh-kadam/setup-lcov@v1

            - name: Run Code Coverage
              run: pnpm run test:coverage

            - name: Get branch names
              id: branch-name
              uses: tj-actions/branch-names@v7

            - name: Commit Code Coverage
              uses: stefanzweifel/git-auto-commit-action@v4
              # Don't commit changes to master or develop branches. Assume they are protected.
              if: steps.branch-name.outputs.current_branch != 'master' && steps.branch-name.outputs.current_branch != 'develop'
              with:
                commit_message: "chore: update code coverage"
                commit_options: "--no-verify"
                file_pattern: "lcov.info"
                skip_dirty_check: false
                create_branch: false

            - name: Add Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: lcov.info
                path: lcov.info
              
            - name: Report Code Coverage
              uses: kefasjw/lcov-pull-request-report@v1
              with:
                lcov-file: lcov.info
                github-token: ${{ secrets.GITHUB_TOKEN }}
