name: Test Code Coverage
on:
    push:
        branches:
            - master
    pull_request:

permissions:
    contents: read

jobs:
    coverage:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Bootstrap
              uses: ./.github/actions/bootstrap

            - name: Build
              run: pnpm run build

            - name: Setup lcov
              uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470 # v1
              with:
                  ref: v2.4

            - name: Add swap space
              run: |
                  sudo swapon --show
                  if [ -f /mnt/swapfile ]; then
                    sudo swapoff /mnt/swapfile || true
                    sudo rm /mnt/swapfile
                  fi
                  sudo fallocate -l 16G /mnt/swapfile
                  sudo chmod 600 /mnt/swapfile
                  sudo mkswap /mnt/swapfile
                  sudo swapon /mnt/swapfile
                  sudo swapon --show

            - name: Run Code Coverage
              env:
                  FOUNDRY_THREADS: 1
              run: pnpm run test:coverage

            - name: Add Artifacts
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: lcov.info
                  path: lcov.info

            # This action runs genhtml (which gives an error), but does not support providing arguments to ignore the error
            # - name: Report Code Coverage
            #   uses: zgosalvez/github-actions-report-lcov@5aba2ff56b3dd258ec9916d3b5049dc5994db23e # v7.0.9
            #   with:
            #       coverage-files: lcov.info
            #       github-token: ${{ secrets.GITHUB_TOKEN }}
            #       update-comment: true
