name: Test Code Coverage
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    run-ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: pnpm/action-setup@v2
              with:
                  version: 9

            - name: Install Node dependencies
              run: pnpm install --frozen-lockfile

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Install Foundry dependencies
              run: pnpm run build

            # FYI: currently version 1.14
            - name: Setup lcov
              uses: hrishikesh-kadam/setup-lcov@v1

            - name: Run Code Coverage
              run: pnpm run test:coverage

            - name: Add Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: lcov.info
                  path: lcov.info

            # This action runs genhtml (which gives an error), but does not support providing arguments to ignore the error
            # - name: Report Code Coverage
            #   uses: zgosalvez/github-actions-report-lcov@v3
            #   with:
            #       coverage-files: lcov.info
            #       github-token: ${{ secrets.GITHUB_TOKEN }}
            #       update-comment: true
