name: Lint Check
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Bootstrap
              uses: ./.github/actions/bootstrap

            - name: Run lint check
              run: pnpm run lint:check
