name: Build Size
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    size-check:
        runs-on: ubuntu-latest

        steps:
            - name: Bootstrap
              uses: ./.github/actions/bootstrap

            # Build will fail if a contract is over the size limit
            - name: Contract Size
              run: pnpm run size
