name: Tests - Unit and Invariant
on:
    push:
        branches:
            - master
    pull_request:

permissions:
    contents: read

jobs:
    unit-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Bootstrap
              uses: ./.github/actions/bootstrap

            - name: Restore Foundry build cache
              uses: ./.github/actions/foundry-cache

            - name: Run unit tests
              run: pnpm run test:unit

    invariant-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Bootstrap
              uses: ./.github/actions/bootstrap

            - name: Restore Foundry build cache
              uses: ./.github/actions/foundry-cache

            - name: Run invariant tests
              run: pnpm run test:invariant
