name: Tests - Cross-Chain
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    crosschain-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Bootstrap
              uses: ./.github/actions/bootstrap

            - name: Build
              run: pnpm run build

            - name: Run cross-chain fork tests
              run: pnpm run test:crosschainfork
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
