name: Tests - OCG Proposals
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    proposal-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Bootstrap
              uses: ./.github/actions/bootstrap

            - name: Build
              run: pnpm run build

            - name: Run proposal simulation tests
              run: pnpm run test:proposal
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
