name: Tests - Fork
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    run-ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: pnpm/action-setup@v2
              with:
                  version: 9

            - name: Install Node dependencies
              run: pnpm install --frozen-lockfile

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Install Foundry dependencies
              run: pnpm run build

            - name: Run fork tests
              run: pnpm run test:fork
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
